### ISSUE TITLE
输入框上方语音图标无法点击

### ISSUE THREAD

**Issue by Banise** [lclichen/LiteLoaderQQNT-TTS#1]
![image](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/91298198/b2254b3d-dfa3-4a8a-89e6-ca5b8beae2f8)
liteloader系列版本
![image](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/91298198/4e19a418-35c6-4b27-ac74-e097eaa1db1f)
![image](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/91298198/1d964a44-03ea-4d15-96ed-2456879ed83c)
其他拓展
![image](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/91298198/4a178562-04f9-4e23-97c4-d26d7297ed0b)
插件设置(均为默认)

**Comment by lclichen** [comment]
啊有可能是接口的问题？返回音频好像挺慢的，要等好几秒才能收到返回的音频，推荐自建服务自己玩（）

**Comment by Banise** [comment]
> 返回

确定了,  就是返回的慢并不是没有反应  过几秒就可以了
按钮点击后没有反馈导致我误以为无法点击
