### ISSUE TITLE
该插件会导致liteloader无法正常工作

### ISSUE THREAD

**Issue by molanp** [lclichen/LiteLoaderQQNT-TTS#12]
如题，是在切换依赖后的版本里产生的，旧版本无问题

**Comment by molanp** [comment]
[0.5.0](https://github.com/lclichen/LiteLoaderQQNT-TTS/releases/tag/0.5.0)版本没有问题，问题是0.6.0产生的

**Comment by sha7dowXX** [comment]
同样的问题

**Comment by lclichen** [comment]
由于LLAPI已弃用，需要独立引入euphony依赖并将其插件文件夹命名为euphony，如果依赖引入不正确则无法正常工作。
