### ISSUE TITLE
语音时长错误

### ISSUE THREAD

**Issue by AnsonGames** [lclichen/LiteLoaderQQNT-TTS#13]
![3bd87001e033d53842ecfe7fc185756f](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/131215887/030ff8cd-2f8e-462c-90d1-245442cfd861)
![9815386ccaaf2f529fddc44de35f8a77](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/131215887/adee1878-34b2-450d-aff9-c87b7fc9bd6b)

**Comment by lclichen** [comment]
> ![3bd87001e033d53842ecfe7fc185756f](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/131215887/030ff8cd-2f8e-462c-90d1-245442cfd861)
> ![9815386ccaaf2f529fddc44de35f8a77](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/131215887/adee1878-34b2-450d-aff9-c87b7fc9bd6b)
> 

这个应该是音频发送的结果？下次更新会改一下嘟

**Comment by molanp** [comment]
个人觉得，能用就行
~~下次我交个pr把配置列表写出来~~

**Comment by lclichen** [comment]
新的release包已修，但是因为太小了没有提新版本（）

**Comment by AnsonGames** [comment]
谢谢大佬
