### ISSUE TITLE
[bug]qq崩溃

### ISSUE THREAD

**Issue by yhzcake** [lclichen/LiteLoaderQQNT-TTS#16]
liteloader和本插件版本最新
发送语音就会崩溃
大概是语音文件就绪向服务器发送的时候,因为重启qq显示发送了语音但是红色感叹号
![image](https://github.com/user-attachments/assets/395b34b2-ec2f-4204-9e67-d9bb20b3ce25)

**Comment by lclichen** [comment]
如果是启用了发送预览的话，请阅读压缩包中的ReadMe，本插件暂时与star rail主题不兼容，主题似乎会修改前端导致发送预览出现问题，我这边短期内可能不太有时间处理这个问题。
（如果没有开启预览的话，能否提供您的插件列表或QQ的debug记录，便于我这边复现问题？）

**Comment by yhzcake** [comment]
额,发送预览是什么?

**Comment by lclichen** [comment]
目前逻辑是都有一个前端显示生成中的弹窗，然后开启发送预览的话会保留这个弹窗用于试听，不开启就自动发送了（emmmm但是我不确定如果时间太长会不会导致这个临时的提示窗口也和主题有冲突）

**Comment by yhzcake** [comment]
我没看到有关你说的试听的设置和这个功能？点转换按钮就直接发出去了
明天我发插件列表给你，另外装liteloader有办法保存日志之类的东西吗，有的话我发日志

**Comment by lclichen** [comment]
可以参考[这里](https://liteloaderqqnt.github.io/docs/introduction.html#%E8%B0%83%E8%AF%95%E4%BB%A3%E7%A0%81)
![image](https://github.com/user-attachments/assets/20aa4756-762f-4fb1-90cd-16906ee24b52)
然后应该还会生成一个log文件，和终端输出的内容一样，我得晚上才能看下他的存储位置。

另外，可以先确认一下前置的插件[Euphony](https://github.com/xtaw/LiteLoaderQQNT-Euphony)正确安装，确认配置文件（在设置中打开配置文件夹）是否有内容，并查看同一个文件夹下的tts@[datetime].[format]（可能是wav）、tts@[datetime].[format].wav、ptt/tts@[datetime].[format].pcm.silk的存在情况，以便确认出现bug时的程序进度。

**Comment by yhzcake** [comment]
忘记了,今天更新插件想起来了
[管理员 Windows PowerShell.txt](https://github.com/user-attachments/files/16744962/Windows.PowerShell.txt)
这是log
![image](https://github.com/user-attachments/assets/d27a1122-bb94-43f5-8ea3-facd0d3a7a1f)
这是data/text-to-speech文件夹里面的文件

**Comment by lclichen** [comment]
确实是star rail主题的问题。。。那可能是等待后端返回数据的时间太久了，然后已经被主题刷新了元素。。。

**Comment by yhzcake** [comment]
好的，这个主题插件兼容性问题好多，我去那边开个issue看看他会不会修吧

**Comment by lclichen** [comment]
版本更新修订了预览开关的管理范围，现在在使用主题时关闭预览应该就可以了。

**Comment by yhzcake** [comment]
[2024.9.11.txt](https://github.com/user-attachments/files/16958160/2024.9.11.txt)
还是崩,开预览直接崩不开老位置崩,语音转完甚至往出发了甚至这次发出去了,但是还是崩

**Comment by yhzcake** [comment]
感觉应该不是这边问题了,去starrail那边发个看看
