### ISSUE TITLE
qq占用率异常

### ISSUE THREAD

**Issue by ReallyChooseC** [lclichen/LiteLoaderQQNT-TTS#17]
如题，禁用该插件后正常

**Comment by lclichen** [comment]
请问有更多可供参考的信息吗？我这边暂时没出现类似的情况

**Comment by ReallyChooseC** [comment]
> 请问有更多可供参考的信息吗？我这边暂时没出现类似的情况

如果有需要日志之类的，我可以提供（不过请告诉我日志文件在哪）

**Comment by lclichen** [comment]
可以尝试先更新一下新版本的插件看还有没有相同问题（然后日志的话可能要用Chii那个插件在QQ里面启用控制台，或者用debug模式开启QQ

**Comment by ReallyChooseC** [comment]
> 可以尝试先更新一下新版本的插件看还有没有相同问题（然后日志的话可能要用Chii那个插件在QQ里面启用控制台，或者用debug模式开启QQ

我会尝试的

**Comment by ReallyChooseC** [comment]
> 可以尝试先更新一下新版本的插件看还有没有相同问题（然后日志的话可能要用Chii那个插件在QQ里面启用控制台，或者用debug模式开启QQ

更新了之后就没有出现过这个问题了
