### ISSUE TITLE
聊天框按钮

### ISSUE THREAD

**Issue by 888pppj** [lclichen/LiteLoaderQQNT-TTS#2]
聊天框的按钮点不动是什么情况

**Comment by wang4386** [comment]
同样的情况，我也是点不动

**Comment by lclichen** [comment]
也许需要多等几秒？
参阅：https://github.com/lclichen/LiteLoaderQQNT-TTS/issues/1

**Comment by jhqwqmc** [comment]
![image](https://github.com/lclichen/LiteLoaderQQNT-TTS/assets/113768629/6b017070-41f1-49b1-9eb0-173607474c97)
疯狂报错没办法使用

**Comment by lclichen** [comment]
> ![image](https://private-user-images.githubusercontent.com/113768629/309499321-6b017070-41f1-49b1-9eb0-173607474c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjE3ODAsIm5iZiI6MTcwOTYyMTQ4MCwicGF0aCI6Ii8xMTM3Njg2MjkvMzA5NDk5MzIxLTZiMDE3MDcwLTQxZjEtNDliMS05ZWIwLTE3MzYwNzQ3NGM5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNjUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGIzZGFiMThlMDA3NjljNjcwZjg1NDdhYTMxMzgyMzI3MDNjYTc4YWUyOGE1NzM4NGU4YjZlM2VjZDhlMzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5wprHwbtXZhHyL_comh0KidTxxyeFxo0uz0w9Exsks) 疯狂报错没办法使用

请将[ffmpeg (包括 ffprobe)](https://ffmpeg.org/)添加至环境变量

**Comment by canglaoshifu** [comment]
俺也一样

**Comment by lclichen** [comment]
如果可能的话，希望能提供更多的信息？

**Comment by 1592363624** [comment]
> ![image](https://private-user-images.githubusercontent.com/113768629/309499321-6b017070-41f1-49b1-9eb0-173607474c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTc3MjUsIm5iZiI6MTcxMDkxNzQyNSwicGF0aCI6Ii8xMTM3Njg2MjkvMzA5NDk5MzIxLTZiMDE3MDcwLTQxZjEtNDliMS05ZWIwLTE3MzYwNzQ3NGM5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNjUwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWQ1Yjg0MDgxYmZmYjhlYjY5OTA2NjU5YmU5MmYwM2I1N2QxMTFjM2IwZjQ2NzY1Mzk4YjZjMjE0NTk4MGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nlLbwHoQCsTBzhS89f_CW5ptsHGfTc5LVp0zQbBZM80) 疯狂报错没办法使用

QQ怎么搞得控制台调试的

**Comment by lclichen** [comment]
> QQ怎么搞得控制台调试的

安个插件，Chii DevTools，然后就可以F12了（）
