### ISSUE TITLE
用户交互没有提示/动态显示的问题

### ISSUE THREAD

**Issue by lclichen** [lclichen/LiteLoaderQQNT-TTS#3]
如果点击按钮长时间没反应可能是示例API延迟较高的问题，由于目前能找到的vits开放API可能较少，推荐自建vits或GPT-SoVITS接口使用本插件。

**Comment by lclichen** [comment]
赶完论文会尝试加入一些操作反馈之类的功能，请耐心等待~谢谢~

**Comment by useduudm** [comment]
本地搭建的api应用之后点了依旧没反应是因为什么呢

**Comment by useduudm** [comment]
你好 新版本的config疑似有点问题 直接用完全没反应 将上个版本的config覆写进新版本之后可以正常运行

**Comment by lclichen** [comment]
> 你好 新版本的config疑似有点问题 直接用完全没反应 将上个版本的config覆写进新版本之后可以正常运行

请问是搭建的什么api？gpt-sovits因为还没有稳定的接口所以可能会存在不同版本间参数不一致的情况，有能力的话推荐使用自定义接口

然后新版本会重新初始化一次配置文件然后更新config的存储位置，不确定会不会跟这个有一定关系？

**Comment by useduudm** [comment]
> > 你好 新版本的config疑似有点问题 直接用完全没反应 将上个版本的config覆写进新版本之后可以正常运行
> 
> 请问是搭建的什么api？gpt-sovits因为还没有稳定的接口所以可能会存在不同版本间参数不一致的情况，有能力的话推荐使用自定义接口
> 
> 然后新版本会重新初始化一次配置文件然后更新config的存储位置，不确定会不会跟这个有一定关系？

搭建的是simple vits的api呢 您指的是在更新储存位置之后会在data文件夹中生成新的config是吗 我是直接将旧版本的setting.json覆盖到data文件夹的 之后就可以正常使用了 在此之前按tts按钮都是没反应的

**Comment by lclichen** [comment]
> > > 你好 新版本的config疑似有点问题 直接用完全没反应 将上个版本的config覆写进新版本之后可以正常运行
> > 
> > 
> > 请问是搭建的什么api？gpt-sovits因为还没有稳定的接口所以可能会存在不同版本间参数不一致的情况，有能力的话推荐使用自定义接口
> > 然后新版本会重新初始化一次配置文件然后更新config的存储位置，不确定会不会跟这个有一定关系？
> 
> 搭建的是simple vits的api呢 您指的是在更新储存位置之后会在data文件夹中生成新的config是吗 我是直接将旧版本的setting.json覆盖到data文件夹的 之后就可以正常使用了 在此之前按tts按钮都是没反应的

啊是的，因为之前是直接在插件目录保存配置文件的，会被版本更新覆盖掉，所以这次改了保存位置，然而还是需要重新配置一下参数（影响使用了不好意思🥹

**Comment by zyzdai** [comment]
[text_to_speech] [转换出错] TypeError: Cannot read properties of undefined (reading 'vits')
    at call_tts (local:///C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT-main\plugins\text_to_speech\src\renderer.js:12:50)

**Comment by lclichen** [comment]
由于忘记了json文件没有办法注释所以出现了一些问题，最新版本已经修复，感谢molanp
同时增加了简单的用户交互提示，会在请求过程中在图标处弹出提示。

**Comment by molanp** [comment]
> 由于忘记了json文件没有办法注释所以出现了一些问题，最新版本已经修复，感谢molanp
> 同时增加了简单的用户交互提示，会在请求过程中在图标处弹出提示。

你的部分修改似乎有误
比如`LiteLoadet.api.config.set`方法的第一个参数，
实测后发现对应的是当前插件数据文件夹下的要储存文件名称


然后关于路径中使用`/`而不是`join`方法进行拼接，在非中文系统上可能会导致一些问题
~~比如日文操作系统分隔符是$~~

**Comment by molanp** [comment]
@lclichen

**Comment by lclichen** [comment]
> > 由于忘记了json文件没有办法注释所以出现了一些问题，最新版本已经修复，感谢molanp
> > 同时增加了简单的用户交互提示，会在请求过程中在图标处弹出提示。
> 
> 你的部分修改似乎有误
> 比如`LiteLoader.api.config.set`方法的第一个参数，
> 实测后发现对应的是当前插件数据文件夹下的要储存文件名称
> @lclichen 
> 
> 
> 然后关于路径中使用`/`而不是`join`方法进行拼接，在非中文系统上可能会导致一些问题
> ~~比如日文操作系统分隔符是$~~

但是我这边实测的`LiteLoader.api.config.set`方法第一个参数是slug（和官方写法一致，这也和官方仓库中的实现一致）

路径后面我再改一下，这个是因为我当时测试时set方法用文件名称就会新建一个config.json的文件夹在data路径中，然后排查问题的时候改了没有改回去

**Comment by molanp** [comment]
> > > 由于忘记了json文件没有办法注释所以出现了一些问题，最新版本已经修复，感谢molanp
> > > 同时增加了简单的用户交互提示，会在请求过程中在图标处弹出提示。
> > 
> > 你的部分修改似乎有误
> > 比如`LiteLoader.api.config.set`方法的第一个参数，
> > 实测后发现对应的是当前插件数据文件夹下的要储存文件名称
> > @lclichen 
> > 
> > 
> > 然后关于路径中使用`/`而不是`join`方法进行拼接，在非中文系统上可能会导致一些问题
> > ~~比如日文操作系统分隔符是$~~
> 
> 但是我这边实测的`LiteLoader.api.config.set`方法第一个参数是slug（和官方写法一致，这也和官方仓库中的实现一致）
> 
> 路径后面我再改一下，这个是因为我当时测试时set方法用文件名称就会新建一个config.json的文件夹在data路径中，然后排查问题的时候改了没有改回去

我测试写的时候只测试了读取，等会再看看保存

**Comment by molanp** [comment]
呃，看到奇怪的存储位置了，这就修
